# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreviewDisplayGui.ui'
#
# Created: Sat Jun 21 16:55:36 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PreviewDisplayWnd(object):
    def setupUi(self, PreviewDisplayWnd):
        PreviewDisplayWnd.setObjectName(_fromUtf8("PreviewDisplayWnd"))
        PreviewDisplayWnd.resize(739, 618)
        self.centralwidget = QtGui.QWidget(PreviewDisplayWnd)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.colorMaxSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.colorMaxSpinBox.setEnabled(False)
        self.colorMaxSpinBox.setDecimals(4)
        self.colorMaxSpinBox.setObjectName(_fromUtf8("colorMaxSpinBox"))
        self.verticalLayout.addWidget(self.colorMaxSpinBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.colorMinSlider = QtGui.QSlider(self.centralwidget)
        self.colorMinSlider.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.colorMinSlider.sizePolicy().hasHeightForWidth())
        self.colorMinSlider.setSizePolicy(sizePolicy)
        self.colorMinSlider.setOrientation(QtCore.Qt.Vertical)
        self.colorMinSlider.setObjectName(_fromUtf8("colorMinSlider"))
        self.horizontalLayout_2.addWidget(self.colorMinSlider)
        self.colorMaxSlider = QtGui.QSlider(self.centralwidget)
        self.colorMaxSlider.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.colorMaxSlider.sizePolicy().hasHeightForWidth())
        self.colorMaxSlider.setSizePolicy(sizePolicy)
        self.colorMaxSlider.setOrientation(QtCore.Qt.Vertical)
        self.colorMaxSlider.setObjectName(_fromUtf8("colorMaxSlider"))
        self.horizontalLayout_2.addWidget(self.colorMaxSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.colorMinSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.colorMinSpinBox.setEnabled(False)
        self.colorMinSpinBox.setDecimals(4)
        self.colorMinSpinBox.setObjectName(_fromUtf8("colorMinSpinBox"))
        self.verticalLayout.addWidget(self.colorMinSpinBox)
        self.colorAutoRadioButton = QtGui.QRadioButton(self.centralwidget)
        self.colorAutoRadioButton.setEnabled(False)
        self.colorAutoRadioButton.setObjectName(_fromUtf8("colorAutoRadioButton"))
        self.verticalLayout.addWidget(self.colorAutoRadioButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.ImageFrameWidget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImageFrameWidget.sizePolicy().hasHeightForWidth())
        self.ImageFrameWidget.setSizePolicy(sizePolicy)
        self.ImageFrameWidget.setObjectName(_fromUtf8("ImageFrameWidget"))
        self.horizontalLayout_3.addWidget(self.ImageFrameWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.CurrentFrameSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.CurrentFrameSpinBox.setEnabled(False)
        self.CurrentFrameSpinBox.setMaximum(100000)
        self.CurrentFrameSpinBox.setObjectName(_fromUtf8("CurrentFrameSpinBox"))
        self.horizontalLayout.addWidget(self.CurrentFrameSpinBox)
        self.FirstFrameButton = QtGui.QPushButton(self.centralwidget)
        self.FirstFrameButton.setEnabled(False)
        self.FirstFrameButton.setObjectName(_fromUtf8("FirstFrameButton"))
        self.horizontalLayout.addWidget(self.FirstFrameButton)
        self.BackFrameButton = QtGui.QPushButton(self.centralwidget)
        self.BackFrameButton.setEnabled(False)
        self.BackFrameButton.setObjectName(_fromUtf8("BackFrameButton"))
        self.horizontalLayout.addWidget(self.BackFrameButton)
        self.PlayButton = QtGui.QPushButton(self.centralwidget)
        self.PlayButton.setEnabled(False)
        self.PlayButton.setObjectName(_fromUtf8("PlayButton"))
        self.horizontalLayout.addWidget(self.PlayButton)
        self.ForwardFrameButton = QtGui.QPushButton(self.centralwidget)
        self.ForwardFrameButton.setEnabled(False)
        self.ForwardFrameButton.setObjectName(_fromUtf8("ForwardFrameButton"))
        self.horizontalLayout.addWidget(self.ForwardFrameButton)
        self.LastFrameButton = QtGui.QPushButton(self.centralwidget)
        self.LastFrameButton.setEnabled(False)
        self.LastFrameButton.setObjectName(_fromUtf8("LastFrameButton"))
        self.horizontalLayout.addWidget(self.LastFrameButton)
        self.CurrentFrameSlider = QtGui.QSlider(self.centralwidget)
        self.CurrentFrameSlider.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentFrameSlider.sizePolicy().hasHeightForWidth())
        self.CurrentFrameSlider.setSizePolicy(sizePolicy)
        self.CurrentFrameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CurrentFrameSlider.setObjectName(_fromUtf8("CurrentFrameSlider"))
        self.horizontalLayout.addWidget(self.CurrentFrameSlider)
        spacerItem = QtGui.QSpacerItem(178, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        PreviewDisplayWnd.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(PreviewDisplayWnd)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PreviewDisplayWnd.setStatusBar(self.statusbar)
        self.actionCompute_Rois = QtGui.QAction(PreviewDisplayWnd)
        self.actionCompute_Rois.setObjectName(_fromUtf8("actionCompute_Rois"))
        self.actionLoad_from_file = QtGui.QAction(PreviewDisplayWnd)
        self.actionLoad_from_file.setObjectName(_fromUtf8("actionLoad_from_file"))
        self.actionSave_to_file = QtGui.QAction(PreviewDisplayWnd)
        self.actionSave_to_file.setObjectName(_fromUtf8("actionSave_to_file"))
        self.actionDelete_Last = QtGui.QAction(PreviewDisplayWnd)
        self.actionDelete_Last.setObjectName(_fromUtf8("actionDelete_Last"))
        self.actionBack_Projection = QtGui.QAction(PreviewDisplayWnd)
        self.actionBack_Projection.setObjectName(_fromUtf8("actionBack_Projection"))
        self.actionAverage = QtGui.QAction(PreviewDisplayWnd)
        self.actionAverage.setObjectName(_fromUtf8("actionAverage"))
        self.actionAdd = QtGui.QAction(PreviewDisplayWnd)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionSubtract = QtGui.QAction(PreviewDisplayWnd)
        self.actionSubtract.setObjectName(_fromUtf8("actionSubtract"))
        self.actionDivide = QtGui.QAction(PreviewDisplayWnd)
        self.actionDivide.setObjectName(_fromUtf8("actionDivide"))
        self.actionMultiply = QtGui.QAction(PreviewDisplayWnd)
        self.actionMultiply.setObjectName(_fromUtf8("actionMultiply"))
        self.actionAdd_image = QtGui.QAction(PreviewDisplayWnd)
        self.actionAdd_image.setObjectName(_fromUtf8("actionAdd_image"))
        self.actionSubtract_image = QtGui.QAction(PreviewDisplayWnd)
        self.actionSubtract_image.setObjectName(_fromUtf8("actionSubtract_image"))
        self.actionDivide_by_image = QtGui.QAction(PreviewDisplayWnd)
        self.actionDivide_by_image.setObjectName(_fromUtf8("actionDivide_by_image"))
        self.actionMultiply_by_image = QtGui.QAction(PreviewDisplayWnd)
        self.actionMultiply_by_image.setObjectName(_fromUtf8("actionMultiply_by_image"))
        self.actionMedian_filter = QtGui.QAction(PreviewDisplayWnd)
        self.actionMedian_filter.setObjectName(_fromUtf8("actionMedian_filter"))
        self.actionGaussian_filter = QtGui.QAction(PreviewDisplayWnd)
        self.actionGaussian_filter.setObjectName(_fromUtf8("actionGaussian_filter"))
        self.actionTemporal_Smoothing = QtGui.QAction(PreviewDisplayWnd)
        self.actionTemporal_Smoothing.setObjectName(_fromUtf8("actionTemporal_Smoothing"))
        self.actionSave_raw_sequence = QtGui.QAction(PreviewDisplayWnd)
        self.actionSave_raw_sequence.setObjectName(_fromUtf8("actionSave_raw_sequence"))
        self.actionSave_traces = QtGui.QAction(PreviewDisplayWnd)
        self.actionSave_traces.setObjectName(_fromUtf8("actionSave_traces"))
        self.actionSave_as_avi = QtGui.QAction(PreviewDisplayWnd)
        self.actionSave_as_avi.setObjectName(_fromUtf8("actionSave_as_avi"))
        self.actionForce_recomputation = QtGui.QAction(PreviewDisplayWnd)
        self.actionForce_recomputation.setObjectName(_fromUtf8("actionForce_recomputation"))
        self.actionSave_as_hd5_table = QtGui.QAction(PreviewDisplayWnd)
        self.actionSave_as_hd5_table.setObjectName(_fromUtf8("actionSave_as_hd5_table"))
        self.actionRoi_options = QtGui.QAction(PreviewDisplayWnd)
        self.actionRoi_options.setObjectName(_fromUtf8("actionRoi_options"))
        self.actionCopy_filepath_to_clipboard = QtGui.QAction(PreviewDisplayWnd)
        self.actionCopy_filepath_to_clipboard.setObjectName(_fromUtf8("actionCopy_filepath_to_clipboard"))
        self.actionRoi_monitor = QtGui.QAction(PreviewDisplayWnd)
        self.actionRoi_monitor.setObjectName(_fromUtf8("actionRoi_monitor"))
        self.actionDelete_number = QtGui.QAction(PreviewDisplayWnd)
        self.actionDelete_number.setObjectName(_fromUtf8("actionDelete_number"))

        self.retranslateUi(PreviewDisplayWnd)
        QtCore.QMetaObject.connectSlotsByName(PreviewDisplayWnd)

    def retranslateUi(self, PreviewDisplayWnd):
        PreviewDisplayWnd.setWindowTitle(_translate("PreviewDisplayWnd", "Preview", None))
        self.colorAutoRadioButton.setText(_translate("PreviewDisplayWnd", "Auto", None))
        self.FirstFrameButton.setText(_translate("PreviewDisplayWnd", "<<", None))
        self.BackFrameButton.setText(_translate("PreviewDisplayWnd", "<", None))
        self.PlayButton.setText(_translate("PreviewDisplayWnd", "P", None))
        self.ForwardFrameButton.setText(_translate("PreviewDisplayWnd", ">", None))
        self.LastFrameButton.setText(_translate("PreviewDisplayWnd", ">>", None))
        self.actionCompute_Rois.setText(_translate("PreviewDisplayWnd", "Compute Roi", None))
        self.actionLoad_from_file.setText(_translate("PreviewDisplayWnd", "Load from file...", None))
        self.actionSave_to_file.setText(_translate("PreviewDisplayWnd", "Save to file", None))
        self.actionDelete_Last.setText(_translate("PreviewDisplayWnd", "Delete Last", None))
        self.actionBack_Projection.setText(_translate("PreviewDisplayWnd", "Back Projection", None))
        self.actionAverage.setText(_translate("PreviewDisplayWnd", "Average", None))
        self.actionAdd.setText(_translate("PreviewDisplayWnd", "Add", None))
        self.actionSubtract.setText(_translate("PreviewDisplayWnd", "Subtract", None))
        self.actionDivide.setText(_translate("PreviewDisplayWnd", "Divide", None))
        self.actionMultiply.setText(_translate("PreviewDisplayWnd", "Multiply", None))
        self.actionAdd_image.setText(_translate("PreviewDisplayWnd", "Add image", None))
        self.actionSubtract_image.setText(_translate("PreviewDisplayWnd", "Subtract image", None))
        self.actionDivide_by_image.setText(_translate("PreviewDisplayWnd", "Divide by image", None))
        self.actionMultiply_by_image.setText(_translate("PreviewDisplayWnd", "Multiply by image", None))
        self.actionMedian_filter.setText(_translate("PreviewDisplayWnd", "Median filter", None))
        self.actionGaussian_filter.setText(_translate("PreviewDisplayWnd", "Gaussian filter", None))
        self.actionTemporal_Smoothing.setText(_translate("PreviewDisplayWnd", "Temporal Smoothing", None))
        self.actionSave_raw_sequence.setText(_translate("PreviewDisplayWnd", "Save raw sequence", None))
        self.actionSave_traces.setText(_translate("PreviewDisplayWnd", "Export traces", None))
        self.actionSave_as_avi.setText(_translate("PreviewDisplayWnd", "Save as avi", None))
        self.actionForce_recomputation.setText(_translate("PreviewDisplayWnd", "Force roi recomputation", None))
        self.actionSave_as_hd5_table.setText(_translate("PreviewDisplayWnd", "Save as hd5 table", None))
        self.actionRoi_options.setText(_translate("PreviewDisplayWnd", "Roi options", None))
        self.actionCopy_filepath_to_clipboard.setText(_translate("PreviewDisplayWnd", "Copy filepath to clipboard", None))
        self.actionRoi_monitor.setText(_translate("PreviewDisplayWnd", "Roi monitor", None))
        self.actionDelete_number.setText(_translate("PreviewDisplayWnd", "Delete number", None))

